- name: Setup
  hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Install gcc
    apt:
      name: gcc
      state: present
      update_cache: yes
  - name: Install pkg-config
    apt:
      name: pkg-config
      state: present
      update_cache: yes
  - name: Install libssl-dev
    apt:
      name: libssl-dev
      state: present
      update_cache: yes
  - name: Install nodejs
    apt:
      name: nodejs
      state: present
      update_cache: yes
  - name: Install docker
    apt:
      name: docker
      state: present
      update_cache: yes
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: yes
  - command: dpkg --remove --force-depends golang-docker-credential-helpers
  - name: Download rust installer
    register: rust_output
    get_url:
      url: https://sh.rustup.rs
      dest: /root/install-rust.sh
  - name: Install rust
    command: sh /root/install-rust.sh -y
  - command: rm -rf vworld
  - command: git clone https://github.com/loicbourgois/vworld.git
  - command: git fetch --all
    args:
      chdir: /root/vworld
  - command: git checkout {{ git_branch }}
    args:
      chdir: /root/vworld
  - command: configuration_name="{{ vworld_config }}" /root/vworld/scripts/vworld-server-start.sh
  # - command: export vworld_root_folder=$(pwd)
  # - command: $vworld_root_folder/scripts/demo.sh
